In [1]:
#вывод без print
a = 10

a + 3
a + 4

14

In [2]:
#вывод с print
print(a + 2)
print(a + 5)

12
15


In [3]:
import numpy as np

In [4]:
# создание массивов

my_list = [4,2,1,5,7]
my_list

[4, 2, 1, 5, 7]

In [5]:
# создание одномерного массива (вектор)
np.array(my_list)



array([4, 2, 1, 5, 7])

In [6]:
# создание двумерного массива (матрица)
my_list = [[10,20,30], [40,50,60]]
np.array(my_list)


array([[10, 20, 30],
       [40, 50, 60]])

In [7]:
my_list = [[10,20,30], [40,50,60]]
print(my_list)

[[10, 20, 30], [40, 50, 60]]


In [8]:
# создание массива из нулей
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [9]:
# массив из целочисленных значений
z.astype("int")

array([0, 0, 0, 0, 0])

In [12]:
# создание двумерного массива из нулей
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
# создание двумерного массива из единиц
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
# метод генерации массивов
# одномерный массив со значениями в линейной последовательности
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [22]:
# Из одномерного массива можно создать двумерный массив
# форма 2-мерного массива должна соответствовать длине исходного 1-мерного массива
arr = np.arange(10)
arr.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [23]:
# 2-массив формой 3*5
# со случайными значениями из равномерного распределения в диапазоне от 0 до 1
np.random.random(5)

array([0.59049389, 0.38917228, 0.77812146, 0.43689713, 0.22141355])

In [24]:
# 2-массив формой 3*5
np.random.random ((3,5))

array([[0.06615312, 0.13835684, 0.76318126, 0.9106869 , 0.62347606],
       [0.06426118, 0.97446289, 0.40802342, 0.88384005, 0.95922653],
       [0.66942559, 0.53471083, 0.39140691, 0.3392447 , 0.85297528]])